[book]
authors = ["Piotr Kurek"]
language = "en"
multilingual = false
src = "src"
title = "Journal"

[output.html.fold]
enable = true

[output.html.code.hidelines]
go = "#"

[output.html.playground]
editable = true